### ISSUE TITLE
Hello from py-lapsolver

### ISSUE THREAD

**Issue by cheind** [berhane/LAP-solvers#1]
Hi, 

just discovered your comparison, great work and thanks for mentioning py-lapsolver! There is currently an on-going [discussion](https://github.com/scipy/scipy/pull/9800) to replace scipy's version with py-lapsolver or other alternatives. Would be nice to see your opinion / benchmark mentioned there too.

Best,
Christoph

**Comment by berhane** [comment]
Thanks, Christoph. I enjoyed doing the benchmarks and I'm glad they will serve some purpose.

I'll add a link to the benchmarks in the SciPy discussion page.

Best,
Berhane

**Comment by cheind** [comment]
Thanks, noted.
