### ISSUE TITLE
Benchmark scipy's new C++ code

### ISSUE THREAD

**Issue by jdmoorman** [berhane/LAP-solvers#2]
As of v1.4.x, SciPy switched to a C++ implementation. This new implementation is likely much faster than the old Python implementation from v1.3.x and earlier. It would be great to see their new code added to your benchmark results!

**Comment by berhane** [comment]
Sure. I've added SciPy 1.4.[0/1] and it looks really good. Please have a look. Thanks.

**Comment by berhane** [comment]
I've added your implementation (laptools) to the list of solvers. The performance is impressive, but the minimum cost is higher than the rest:

<pre>
8 x 8 ...

Cycle  0   lapjv_lapjv    lapjv_lapjv minimum cost 10.290
 lap_lapjv      lap_lapjv minimum cost 10.290
 scipy          scipy minimum cost 10.290
 lapsolver      lapsolver minimum cost 10.290
 laptools_clap   laptools_clap minimum cost 17.277
 munkres        munkres minimum cost 10.290


16 x 16 ...

Cycle  0   lapjv_lapjv    lapjv_lapjv minimum cost 26.474
 lap_lapjv      lap_lapjv minimum cost 26.474
 scipy          scipy minimum cost 26.474
 lapsolver      lapsolver minimum cost 26.474
 laptools_clap   laptools_clap minimum cost 33.950
 munkres        munkres minimum cost 26.474


32 x 32 ...

Cycle  0   lapjv_lapjv    lapjv_lapjv minimum cost 61.405
 lap_lapjv      lap_lapjv minimum cost 61.405
 scipy          scipy minimum cost 61.405
 lapsolver      lapsolver minimum cost 61.405
 laptools_clap   laptools_clap minimum cost 61.576
 munkres        munkres minimum cost 61.405


64 x 64 ...

Cycle  0   lapjv_lapjv    lapjv_lapjv minimum cost 94.507
 lap_lapjv      lap_lapjv minimum cost 94.507
 scipy          scipy minimum cost 94.507
 lapsolver      lapsolver minimum cost 94.507
 laptools_clap   laptools_clap minimum cost 118.526
 munkres        munkres minimum cost 94.507


128 x 128 ...

Cycle  0   lapjv_lapjv    lapjv_lapjv minimum cost 198.544
 lap_lapjv      lap_lapjv minimum cost 198.544
 scipy          scipy minimum cost 198.544
 lapsolver      lapsolver minimum cost 198.544
 laptools_clap   laptools_clap minimum cost 302.607
 munkres        munkres minimum cost 198.544


Package Versions for the current run
Python -  3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20)
[GCC 7.3.0]
lap  -  0.4.0
scipy  -  1.4.1
lapsolver  -  1.1.0
laptools  -  0.1.7
munkres  -  1.1.2


   Matrix_size       8      16      32      64     128
 lapjv_lapjv  [0.00002 0.00001 0.00002 0.00004 0.00009]
   lap_lapjv  [0.00008 0.00003 0.00004 0.00006 0.00013]
       scipy  [0.0001  0.00006 0.00008 0.00021 0.00067]
   lapsolver  [0.00004 0.00002 0.00003 0.00009 0.00036]
laptools_clap  [0.0001  0.00009 0.00012 0.00028 0.00083]
     munkres  [0.00093 0.00599 0.04265 0.38525 4.1628 ]
</pre>

You can check it yourself:
-  `python benchmark-lap-solvers.py --printcost --ncyc 1 --min 8 --max 216`

**Comment by jdmoorman** [comment]
Thanks for taking the initiative on adding our implementation (laptools) to your benchmarks! Our code and API is in a state of flux, so when it settles down I will open a PR here with a correct implementation.

The new scipy benchmarks look good!

**Comment by berhane** [comment]
That sounds good. Good luck!
